# Generated by Django 4.2.13 on 2024-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description_chaivariety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
